/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maincarro;

import javax.swing.JDesktopPane;

/**
 *
 * @author USUARIO
 */
public class Menu extends javax.swing.JFrame {

    private JDesktopPane escritorio;
    
    
    
    public Menu() {
        initComponents();
        escritorio = new JDesktopPane();
        this.setContentPane(escritorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        optMenu = new javax.swing.JMenu();
        optRegistro = new javax.swing.JMenuItem();
        optLista = new javax.swing.JMenuItem();
        optSalir = new javax.swing.JMenuItem();
        optAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        optMenu.setText("Menu");

        optRegistro.setText("Registrar Carro");
        optRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRegistroActionPerformed(evt);
            }
        });
        optMenu.add(optRegistro);

        optLista.setText("Lista de Carros");
        optLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optListaActionPerformed(evt);
            }
        });
        optMenu.add(optLista);

        optSalir.setText("Salir");
        optSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSalirActionPerformed(evt);
            }
        });
        optMenu.add(optSalir);

        jMenuBar1.add(optMenu);

        optAyuda.setText("Ayuda");
        jMenuBar1.add(optAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optListaActionPerformed
        // TODO add your handling code here:
        ListaForm list = new ListaForm();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_optListaActionPerformed

    private void optRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRegistroActionPerformed
        Carros carro = new Carros();
        carro.setVisible(true);
        dispose();
    }//GEN-LAST:event_optRegistroActionPerformed

    private void optSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_optSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu optAyuda;
    private javax.swing.JMenuItem optLista;
    private javax.swing.JMenu optMenu;
    private javax.swing.JMenuItem optRegistro;
    private javax.swing.JMenuItem optSalir;
    // End of variables declaration//GEN-END:variables
}
